---
title: "Paper 3 Annotations"
author: "Danielle McCool"
date: "`r Sys.Date()`"
bibliography: paperpile_paper3.bib
nocite: '@*'
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    thumbnails: false
    lightbox: true
---

```{css echo=FALSE}
.highlight {
  position: relative;
  padding: 10px 10px 10px 45px !important;
  border-left-width: 5px !important;
  border-left-style: solid !important;
  border-radius: 5px !important;
  background-color: #f7f7f7 !important;
}


.highlight::before {
  position: absolute;
  content: attr(pagenum);
  font-size: 1em;
  margin-left: -2.5em;
  font-style: normal;
  color: black;
}

.comment {
  padding: 10px 45px 10px 45px !important;
  border-left-width: 10px !important;
  background-color: white !important;
  font-style: normal !important;
  border-radius: 10px !important;
}

.csl-entry {
  margin-block-end: 20px;
}

```

```{r setup, echo=FALSE, warning=FALSE}
library(knitr)
source("json_parser.R")
```

```{r echo=FALSE, results='asis', warning=FALSE}
json <- readJsonPaperpile()
layoutPapersInHTML(json)
```

## References

